/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author theki
 */
public class InMenugames extends javax.swing.JFrame {
protected s2Prj s1;
protected Games s2;
protected Login s3;
protected Register s4;
protected  Recherche s0;
//protected Store s3;

    /**
     * Creates new form InMenu
     */
    public InMenugames() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        GameB8 = new javax.swing.JButton();
        GameB4 = new javax.swing.JButton();
        GameB2 = new javax.swing.JButton();
        GameB3 = new javax.swing.JButton();
        GameB1 = new javax.swing.JButton();
        GameB5 = new javax.swing.JButton();
        GameB6 = new javax.swing.JButton();
        GameB7 = new javax.swing.JButton();
        GameB9 = new javax.swing.JButton();
        GameB12 = new javax.swing.JButton();
        GameB10 = new javax.swing.JButton();
        GameB11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        UserNAME_ingamem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        UserLastNAME_ingamem = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\assets\\cccreckon.png")); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 950, -1));
        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 312, 1040, 10));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Welcome back");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1130, 350));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GameB8.setIcon(new javax.swing.ImageIcon("D:\\assets\\pupg.png")); // NOI18N
        GameB8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB8ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 250, -1));

        GameB4.setIcon(new javax.swing.ImageIcon("D:\\assets\\hell.png")); // NOI18N
        GameB4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB4ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 250, -1));

        GameB2.setIcon(new javax.swing.ImageIcon("D:\\assets\\wwwwwwww.jpg")); // NOI18N
        GameB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB2ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 240, 330));

        GameB3.setIcon(new javax.swing.ImageIcon("D:\\assets\\ffffff.jpg")); // NOI18N
        GameB3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB3ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 240, -1));

        GameB1.setIcon(new javax.swing.ImageIcon("D:\\assets\\bfffffffff.jpg")); // NOI18N
        GameB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB1ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 250, -1));

        GameB5.setIcon(new javax.swing.ImageIcon("D:\\assets\\gt5.png")); // NOI18N
        GameB5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB5ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 250, 340));

        GameB6.setIcon(new javax.swing.ImageIcon("D:\\assets\\neeed.png")); // NOI18N
        GameB6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB6ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 250, -1));

        GameB7.setIcon(new javax.swing.ImageIcon("D:\\assets\\zeeeee.png")); // NOI18N
        GameB7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GameB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameB7ActionPerformed(evt);
            }
        });
        jPanel4.add(GameB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 250, -1));

        GameB9.setIcon(new javax.swing.ImageIcon("D:\\assets\\aco.png")); // NOI18N
        GameB9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(GameB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, 250, 340));

        GameB12.setIcon(new javax.swing.ImageIcon("D:\\assets\\fallo.png")); // NOI18N
        GameB12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(GameB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, 250, 330));

        GameB10.setIcon(new javax.swing.ImageIcon("D:\\assets\\bf11.png")); // NOI18N
        GameB10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(GameB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 690, 250, 340));

        GameB11.setIcon(new javax.swing.ImageIcon("D:\\assets\\wild.png")); // NOI18N
        GameB11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(GameB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 690, 250, -1));
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 50, 80));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 1110, 1060));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1180, 1420));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1180, 610));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\assets\\9999.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\theki\\Desktop\\assets\\icons8_Close_Window_48px.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, 60));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Store");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Library");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 20));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 280, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\theki\\Desktop\\assets\\icons8_Search_24px.png")); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 30, 50));

        UserNAME_ingamem.setText("1");
        jPanel3.add(UserNAME_ingamem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 70, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_________");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1190, -1));

        UserLastNAME_ingamem.setText("2");
        jPanel3.add(UserLastNAME_ingamem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 70, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 51));
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\theki\\Desktop\\assets\\icons8_User_48px_1.png")); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setOpaque(false);
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, -1, 60));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("_________");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 70, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\theki\\Desktop\\assets\\icons8_Menu_24px.png")); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 24, -1, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_________");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 90));

        setSize(new java.awt.Dimension(1181, 693));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);      
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        declarations ();
        this.setVisible(false);
        s2.setVisible(true);
        s2.UserLastNAME_Games.setText(this.UserLastNAME_ingamem.getText());
        s2.UserNAME_Games.setText(this.UserNAME_ingamem.getText());
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    private void GameB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB2ActionPerformed
       String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       System.out.println(mail);
        System.out.println(pass);
       regiterplaybd(mail,pass,"the witcher 3");
      
       
    }//GEN-LAST:event_GameB2ActionPerformed

    private void GameB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB4ActionPerformed
       String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       
       regiterplaybd(mail,pass,"Hellblade ");
    }//GEN-LAST:event_GameB4ActionPerformed

    private void GameB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB1ActionPerformed
       String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       
       regiterplaybd(mail,pass,"battlefield 3");
    
    }//GEN-LAST:event_GameB1ActionPerformed

    private void GameB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB3ActionPerformed
      String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       
       regiterplaybd(mail,pass,"FIFA 18");
       
       
    }//GEN-LAST:event_GameB3ActionPerformed

    private void GameB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB5ActionPerformed
         String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       
       regiterplaybd(mail,pass,"GTA 5");
    }//GEN-LAST:event_GameB5ActionPerformed

    private void GameB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB6ActionPerformed
          String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       
       regiterplaybd(mail,pass,"need for speed");
    }//GEN-LAST:event_GameB6ActionPerformed

    private void GameB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB7ActionPerformed
        String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       
       regiterplaybd(mail,pass,"Far cry 5");
    }//GEN-LAST:event_GameB7ActionPerformed

    private void GameB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameB8ActionPerformed
       String nommm=this.UserLastNAME_ingamem.getText();
       String prenommm =this.UserNAME_ingamem.getText();
       String mail =getemail(nommm,prenommm);
       String pass=getpwd(nommm,prenommm);
       
       regiterplaybd(mail,pass,"pupg");
    }//GEN-LAST:event_GameB8ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       declarations();
        String rech =jTextField1.getText();
String name=s2.getnomG(rech);
if(name!=null)
{
    s0=new Recherche();
    s0.setVisible(true);
    System.out.println(name);
    s0.essem.setText(name);
    String path= s2.getpathI(name).toString();
     ImageIcon a =new ImageIcon(path);
    s0.tasswira.setIcon(a);
    }//GEN-LAST:event_jLabel5MouseClicked
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InMenugames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InMenugames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InMenugames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InMenugames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InMenugames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GameB1;
    private javax.swing.JButton GameB10;
    private javax.swing.JButton GameB11;
    private javax.swing.JButton GameB12;
    private javax.swing.JButton GameB2;
    private javax.swing.JButton GameB3;
    private javax.swing.JButton GameB4;
    private javax.swing.JButton GameB5;
    private javax.swing.JButton GameB6;
    private javax.swing.JButton GameB7;
    private javax.swing.JButton GameB8;
    private javax.swing.JButton GameB9;
    protected javax.swing.JLabel UserLastNAME_ingamem;
    protected javax.swing.JLabel UserNAME_ingamem;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
protected void declarations ()
{s2=new Games();
//s3=new Store();
}

protected String getnom( String mail)
{
    String la9ab="";
    try {
			Class.forName("oracle.jdbc.OracleDriver");
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
		Statement st=con.createStatement();
		String sql="select nom,prenom  from userr where email='"+mail+"'";
		ResultSet rs=st.executeQuery(sql);
		
		while(rs.next()){
			   
			 la9ab=rs.getString(2);
			                System.out.println(la9ab);        
			 }	
		//user p=new user(Nom,Prenom,email,date,Password,photo);
		rs.close();
		st.close();
		con.close();
		
		}
		 catch (Exception e) {
			
			System.out.println(e);
		}
    return la9ab;
}
protected String getprenom( String mail)
{
    String essm="";
    try {
			Class.forName("oracle.jdbc.OracleDriver");
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
		Statement st=con.createStatement();
		String sql="select nom,prenom  from userr where email='"+mail+"'";
		ResultSet rs=st.executeQuery(sql);
		
		while(rs.next()){
			   
			 essm=rs.getString(1);
			                     
			 }	
		//user p=new user(Nom,Prenom,email,date,Password,photo);
		rs.close();
		st.close();
		con.close();
		
		}
		 catch (Exception e) {
			
			System.out.println(e);
		}
    return essm;
}
protected void declarations2()
{
   
        s1 =new s2Prj();
         s2=new Games();
         s3=new Login();
         s4=new Register();
      
}
protected String getemail(String essm,String lakab)
{
                String emaill="";
                
                
                 	try {
			Class.forName("oracle.jdbc.OracleDriver");
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
		Statement st=con.createStatement();
		String sql="select * from userr where nom='"+lakab+"' and prenom ='"+essm+"'";
                
		ResultSet rs=st.executeQuery(sql);
		
		while(rs.next()){
			 
			 emaill= rs.getString(3) ;
                     
			 }
                //user p=new user(Nom,Prenom,email,date,Password,photo);
		rs.close();
		st.close();
		con.close();
		
		}
		 catch (Exception e) {
			
			System.out.println(e);
		}return emaill ;
}
protected String getpwd(String essm,String lakab)
{
                String pass="";
                
                
                 	try {
			Class.forName("oracle.jdbc.OracleDriver");
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
		Statement st=con.createStatement();
		String sql="select * from userr where nom='"+lakab+"' and prenom ='"+essm+"'";
		ResultSet rs=st.executeQuery(sql);
		
		while(rs.next()){
			 
			 pass= rs.getString(4) ;
                     
			 }
                //user p=new user(Nom,Prenom,email,date,Password,photo);
		rs.close();
		st.close();
		con.close();
		
		}
		 catch (Exception e) {
			
			System.out.println(e);
		}return pass ;
}

protected   void regiterplaybd (String emaill,String pass,String jeu){
		
		 		try {
                                    
                                   
			Class.forName("oracle.jdbc.OracleDriver");
		Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","oracle");
		Statement st=con.createStatement();
                
		String personne="INSERT INTO PLAY VALUES('"+emaill+"','"+pass+"','"+jeu+"')";
               
			int nb=st.executeUpdate(personne);
                        
			if(nb == 1) System.out.println("Insertion effectuée avec succès.");//nombre des lignes inserer
			else System.out.println("Pas d'insertion."); 
			st.close();
			con.close();	
                        
		}
		 catch (Exception e) {
			
			System.out.println(e);
		}
		 
	}
}
